package main

import (
	"fmt"
	"io"
	"net/http"
)

func main() {
	fmt.Println("Welcome to the GET request")
	PerformGetRequest()
}

func PerformGetRequest() {
	const myUrl = "https://httpbin.org/get" //Or we can add /get in the end of the link, It will still get the same response

	response, err := http.Get(myUrl)

	if err != nil {
		panic(err)
	}

	defer response.Body.Close()

	output, err := io.ReadAll(response.Body)

	if err != nil {
		panic(err)
	}

	fmt.Println("The response generated by the get request is : ", string(output))
	fmt.Println("This is the end of the body")
}